// Generated by gencpp from file beginner_tutorials/Message1.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_MESSAGE1_H
#define BEGINNER_TUTORIALS_MESSAGE_MESSAGE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Message1_
{
  typedef Message1_<ContainerAllocator> Type;

  Message1_()
    : data()
    , number(0)  {
    }
  Message1_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , number(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef int32_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::beginner_tutorials::Message1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Message1_<ContainerAllocator> const> ConstPtr;

}; // struct Message1_

typedef ::beginner_tutorials::Message1_<std::allocator<void> > Message1;

typedef boost::shared_ptr< ::beginner_tutorials::Message1 > Message1Ptr;
typedef boost::shared_ptr< ::beginner_tutorials::Message1 const> Message1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::Message1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::Message1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::Message1_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Message1_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.number == rhs.number;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::Message1_<ContainerAllocator1> & lhs, const ::beginner_tutorials::Message1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::Message1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Message1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::Message1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Message1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::Message1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f8a480cda4575b0a5f510728d861e631";
  }

  static const char* value(const ::beginner_tutorials::Message1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf8a480cda4575b0aULL;
  static const uint64_t static_value2 = 0x5f510728d861e631ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/Message1";
  }

  static const char* value(const ::beginner_tutorials::Message1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Message1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
"int32 number\n"
;
  }

  static const char* value(const ::beginner_tutorials::Message1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Message1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Message1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Message1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::Message1_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_MESSAGE1_H
